name: Github Action for manim rendering
description: GitHub Action to render manim videos
author: Tony Wang
inputs:
  source_file:
    description: The source user file to render videos from
    required: true
outputs:
  video_path:
    description: The video folder path of rendered videos
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.source_file }}
branding:
  icon: camera
  color: blue
